<?php

namespace App\Constants;

class TransactionActivityConstants
{

    const CREDIT_PROVIDER_USER = "CREDIT_PROVIDER_USER";
    const PROVIDER = "PROVIDER";
    const FASTEST_FINGER = "FASTEST_FINGER";
    const FASTEST_FINGER_REFERRER_BONUS = "FASTEST_FINGER_REFERRER_BONUS";
    const SURVEY = "SURVEY";
    const CURRENCY_EXCHANGE = "CURRENCY_EXCHANGE";
    const FUND_WITH_FLUTTERWAVE = "FUND_WITH_FLUTTERWAVE";
    const REFERRAL_BONUS = "REFERRAL_BONUS";
    const SIGNUP_BONUS = "SIGNUP_BONUS";
    const JOINED_ROOM_BONUS = "JOINED_ROOM_BONUS";
    const WITHDRAW_WITH_BANK = "WITHDRAW_WITH_BANK";
    const ACTIVITY_LEVEL = "ACTIVITY_LEVEL";
    const SYSTEM_CREDIT = "SYSTEM_CREDIT";
    const WALLET_TRANSFER = "WALLET_TRANSFER";
    const SUBSCRIBE_TO_NETWORK_PLAN = "SUBSCRIBE_TO_NETWORK_PLAN";
    const SUBSCRIPTION_DAILY_ACTIVITY = "SUBSCRIPTION_DAILY_ACTIVITY";
    const FUND_WITH_BANK = "FUND_WITH_BANK";
    const WITHDRAWAL_REFUND = "WITHDRAWAL_REFUND";
    const CREATE_AD = "CREATE_AD";
    const AD_SHARE_ACTIVITY_BONUS = "AD_SHARE_ACTIVITY_BONUS";
    const STORYBOOK_EARNING = "STORYBOOK_EARNING";
    const CRYPTO_MINING = "CRYPTO_MINING";

    const ADMIN_FILTER_OPTIONS = [
        self::CREDIT_PROVIDER_USER => "CREDIT PROVIDER USER",
        self::PROVIDER => "PROVIDER",
        self::FASTEST_FINGER => "FASTEST FINGER",
        self::FASTEST_FINGER_REFERRER_BONUS => "FASTEST FINGER REFERRER BONUS",
        self::SURVEY => "SURVEY",
        self::CURRENCY_EXCHANGE => "CURRENCY EXCHANGE",
        self::FUND_WITH_FLUTTERWAVE => "FUND WITH FLUTTERWAVE",
        self::REFERRAL_BONUS => "REFERRAL BONUS",
        self::SIGNUP_BONUS => "SIGNUP BONUS",
        self::JOINED_ROOM_BONUS => "JOINED ROOM BONUS",
        self::WITHDRAW_WITH_BANK => "WITHDRAW WITH BANK",
        self::ACTIVITY_LEVEL => "ACTIVITY LEVEL",
        self::SYSTEM_CREDIT => "SYSTEM CREDIT",
        self::WALLET_TRANSFER => "WALLET TRANSFER",
        self::SUBSCRIBE_TO_NETWORK_PLAN => "SUBSCRIBE TO NETWORK PLAN",
        self::SUBSCRIPTION_DAILY_ACTIVITY => "SUBSCRIPTION DAILY ACTIVITY",
        self::FUND_WITH_BANK => "FUND WITH BANK",
        self::WITHDRAWAL_REFUND => "WITHDRAWAL REFUND",
        self::STORYBOOK_EARNING => "STORYBOOK EARNING",
        self::CRYPTO_MINING => "CRYPTO MINING"
    ];
}
